[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
fs_permissions = [{ access = "read", path = "./" }]

[profile.default.fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true
number_underscore = "thousands"
